name: CI

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install Task
        uses: go-task/setup-task@v2
        with:
          version: "3.x"

      - name: Format
        run: |
          task format
          git diff --exit-code

      - name: Lint
        run: task lint

      - name: Tests
        run: task test
